(function(){var R='/Users/picklejuice/Desktop/dMIC60 Graphs Code and Data/Common_Width_2026-09-23/Layout_Data',O='/Users/picklejuice/Desktop/dMIC60 Graphs Code and Data/Common_Width_2026-09-23';
function read(p){var f=new File(p);f.encoding='UTF-8';f.open('r');var x=eval('('+f.read()+')');f.close();return x;}
function js(x){if(x===null||typeof x==='undefined')return'null';if(typeof x==='string')return '"'+x.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r/g,'\\r').replace(/\n/g,'\\n')+'"';if(typeof x==='number'||typeof x==='boolean')return String(x);var a=[],k;if(x instanceof Array){for(k=0;k<x.length;k++)a.push(js(x[k]));return '['+a.join(',')+']';}for(k in x)if(x.hasOwnProperty(k))a.push(js(k)+':'+js(x[k]));return '{'+a.join(',')+'}';}
function b(p){var q=p.geometricBounds;return[q[0],q[1],q[2],q[3]];}function unlock(p){var a=[],x=p;while(x&&x.typename!=='Document'){if(x.locked){a.push(x);x.locked=false;}x=x.parent;}return a;}function relock(a){for(var i=a.length-1;i>=0;i--)a[i].locked=true;}
var req=read(R+'/REQUEST.json'),plan=read(R+'/'+req.name.replace('.ai','')+'_ROW_PLAN.json'),d=app.documents.getByName(req.name);d.activate();d=app.activeDocument;if(!d.saved||d.fullName.fsName!==plan.path)throw Error('Live changes/path mismatch');var cache={};function get(id){if(!cache[id])cache[id]=d.getPageItemFromUuid(id);return cache[id];}function chk(o){var p=get(o.id),bb=b(p);for(var k=0;k<4;k++)if(Math.abs(bb[k]-o.before[k])>.005)throw Error('Changed geometry '+o.id+' '+bb[k]+' / '+o.before[k]);}
for(var i=0;i<plan.paths.length;i++)chk(plan.paths[i]);for(i=0;i<plan.texts.length;i++){chk(plan.texts[i]);if(get(plan.texts[i].id).contents!==plan.texts[i].original)throw Error('Changed text');}for(i=0;i<plan.items.length;i++)chk(plan.items[i]);
var out={name:d.name,paths:[],texts:[],items:[]};
for(var i=0;i<plan.paths.length;i++){var o=plan.paths[i],p=get(o.id),locks=unlock(p);if(p.pathPoints.length!==o.after.length)throw Error('Point count');for(var j=0;j<o.after.length;j++){var v=p.pathPoints[j];v.anchor=o.after[j][0];v.leftDirection=o.after[j][1];v.rightDirection=o.after[j][2];}if(p.name==='Verified box body - 32 pt')p.name='Verified box body - 24 pt';relock(locks);out.paths.push({id:o.id,b:b(p),role:o.role});}
for(i=0;i<plan.texts.length;i++){var o=plan.texts[i],t=get(o.id),locks=unlock(t);if(o.content!==undefined){t.contents=o.content;t.textRange.paragraphAttributes.justification=Justification.CENTER;}var bb=b(t),dx=o.dx||0,dy=o.dy||0;if(o.targetCenter!==undefined)dx=o.targetCenter-(bb[0]+bb[2])/2;if(o.targetTop!==undefined)dy=o.targetTop-bb[1];t.translate(dx,dy);relock(locks);out.texts.push({id:o.id,text:t.contents,b:b(t)});}
function fx(x,u){return u.target[0]+(x-u.source[0])*u.scale;}function fy(y,u){return u.target[1]+(y-u.source[1])*u.scale;}
for(i=0;i<plan.items.length;i++){var o=plan.items[i],p=get(o.id),locks=unlock(p);if(o.uniform){var u=o.uniform;p.resize(u.scale*100,u.scale*100,true,true,true,true,100,Transformation.TOPLEFT);var bb=b(p);p.translate(fx(o.before[0],u)-bb[0],fy(o.before[1],u)-bb[1]);}else p.translate(o.dx||0,o.dy||0);relock(locks);out.items.push({id:o.id,b:b(p)});}
for(i=0;plan.restoreTexts&&i<plan.restoreTexts.length;i++){var o=plan.restoreTexts[i],t=get(o.id),u=o.uniform,locks=unlock(t);t.resize(100/u.scale,100/u.scale,true,true,true,true,100,Transformation.CENTER);var bb=b(t);t.translate(fx((o.before[0]+o.before[2])/2,u)-(bb[0]+bb[2])/2,fy((o.before[1]+o.before[3])/2,u)-(bb[1]+bb[3])/2);relock(locks);out.texts.push({id:o.id,text:t.contents,b:b(t)});}
for(i=0;plan.postTexts&&i<plan.postTexts.length;i++){var o=plan.postTexts[i],t=get(o.id),bb=b(t);t.translate(o.targetLeft-bb[0],o.targetTop-bb[1]);}
if(plan.artboardBottom!==undefined){var a=d.artboards[0].artboardRect;d.artboards[0].artboardRect=[a[0],a[1],a[2],plan.artboardBottom];}
d.selection=null;app.redraw();d.save();File(d.fullName.fsName).copy(O+'/After_AI/'+d.name);var f=new File(R+'/'+d.name.replace('.ai','')+'_ROW_RESULT.json');f.encoding='UTF-8';f.open('w');f.write(js(out));f.close();return d.name+': row layout saved; '+out.paths.length+' vector paths, '+out.texts.length+' text positions, '+out.items.length+' groups/items';})();
