(function(){var R='/Users/picklejuice/Desktop/dMIC60 Graphs Code and Data/Common_Width_2026-09-23/Layout_Data';function read(p){var f=new File(p);f.open('r');var x=eval('('+f.read()+')');f.close();return x;}function js(x){if(x===null||typeof x==='undefined')return'null';if(typeof x==='string')return '"'+x.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r/g,'\\r').replace(/\n/g,'\\n')+'"';if(typeof x==='number'||typeof x==='boolean')return String(x);var a=[],k;if(x instanceof Array){for(k=0;k<x.length;k++)a.push(js(x[k]));return '['+a.join(',')+']';}for(k in x)if(x.hasOwnProperty(k))a.push(js(k)+':'+js(x[k]));return '{'+a.join(',')+'}';}function b(t){var q=t.geometricBounds;return[q[0],q[1],q[2],q[3]];}function visible(x){while(x&&x.typename!=='Document'){if(x.typename==='Layer'&&!x.visible)return false;if(x.typename!=='Layer'&&x.hidden)return false;x=x.parent;}return true;}
var req=read(R+'/REQUEST.json'),d=app.documents.getByName(req.name);d.activate();d=app.activeDocument;var out={name:d.name,path:d.fullName.fsName,saved:d.saved,artboard:d.artboards[0].artboardRect,top:[],texts:[],rasters:[]},seen={};
function layer(l){for(var i=0;i<l.pageItems.length;i++){var p=l.pageItems[i];if(p.parent.typename!=='Layer'||seen[p.uuid])continue;seen[p.uuid]=true;out.top.push({id:p.uuid,type:p.typename,name:p.name,b:b(p),hidden:p.hidden,locked:p.locked,visible:visible(p),layer:l.name});}for(var i=0;i<l.layers.length;i++)layer(l.layers[i]);}
for(var i=0;i<d.layers.length;i++)layer(d.layers[i]);
for(var i=0;i<d.textFrames.length;i++){var t=d.textFrames[i];if(!visible(t)||!t.contents)continue;var cs=[];for(var j=0;j<t.characters.length;j++){var c=t.characters[j],a=c.characterAttributes;cs.push({c:c.contents,font:a.textFont.name,size:a.size,shift:a.baselineShift,h:a.horizontalScale,v:a.verticalScale,leading:a.leading,auto:a.autoLeading});}var par=t,chain=[];while(par&&par.typename!=='Document'){if(par.uuid)chain.push(par.uuid);par=par.parent;}out.texts.push({id:t.uuid,text:t.contents,b:b(t),chars:cs,chain:chain,locked:t.locked});}
for(var i=0;i<d.rasterItems.length;i++){var p=d.rasterItems[i];if(visible(p))out.rasters.push({id:p.uuid,b:b(p),width:p.width,height:p.height});}

out.roots=[];
var rootMap={'Fig2.ai':['808'],'Fig3.ai':['435','1843','525','959','2078','1048','2315','1464','1534','1645','1753','7293'],'Fig4.ai':['383','608'],'FigS4.ai':['436','1014']};
var ids=rootMap[d.name]||[];
function color(c){if(!c)return null;if(c.typename==='RGBColor')return[c.red,c.green,c.blue];if(c.typename==='GrayColor')return['gray',c.gray];return c.typename;}
function collect(g,a){for(var k=0;k<g.pageItems.length;k++){var p=g.pageItems[k];if(p.parent!==g)continue;if(p.typename==='PathItem'){var pts=[];for(var j=0;j<p.pathPoints.length;j++){var q=p.pathPoints[j];pts.push([q.anchor,q.leftDirection,q.rightDirection]);}a.paths.push({id:p.uuid,name:p.name,b:b(p),visible:visible(p),clipping:p.clipping,fill:p.filled?color(p.fillColor):null,stroke:p.stroked?color(p.strokeColor):null,strokeWidth:p.strokeWidth,points:pts});}else if(p.typename==='GroupItem'){a.groups.push({id:p.uuid,name:p.name,b:b(p),clipped:p.clipped});collect(p,a);}}}
for(var z=0;z<ids.length;z++){var g=d.getPageItemFromUuid(ids[z]),a={id:ids[z],name:g.name,b:b(g),paths:[],groups:[]};collect(g,a);out.roots.push(a);}

var f=new File(R+'/'+req.name.replace('.ai','')+'_NORMALIZED.json');f.encoding='UTF-8';f.open('w');f.write(js(out));f.close();return req.name+': '+out.top.length+' top-level items, '+out.texts.length+' visible text frames';})();
