# Native vector replacements: original editable schematic generators were unavailable.
# These diagrams describe the reviewed workflow; they do not fabricate microscopy.
suppressPackageStartupMessages(library(grid))
script <- normalizePath(gsub('~+~',' ',sub('^--file=','',grep('^--file=',commandArgs(FALSE),value=TRUE)[1]),fixed=TRUE))
root <- dirname(dirname(script));source(file.path(dirname(script),'figure_style.R'))
out <- file.path(root,'results/full_figures');dir.create(out,recursive=TRUE,showWarnings=FALSE)
box <- function(x,y,w,h,label,fill='grey96',bold=FALSE) {
 grid.roundrect(x,y,w,h,r=unit(3,'pt'),gp=gpar(fill=fill,col='grey45',lwd=.5))
 grid.text(label,x,y,gp=gpar(fontfamily=FIG_FONT,fontsize=7,fontface=if(bold)'bold' else 'plain',lineheight=1.25))
}
link <- function(x,y,xx,yy,dashed=FALSE,arrowhead=TRUE) grid.lines(c(x,xx),c(y,yy),gp=gpar(col='grey35',lwd=.6,lty=if(dashed)2 else 1),arrow=if(arrowhead)arrow(length=unit(3,'pt'),type='closed')else NULL)
label <- function(x,y,s,bold=FALSE) grid.text(s,x,y,gp=gpar(fontfamily=FIG_FONT,fontsize=if(bold)8 else 7,fontface=if(bold)'bold' else 'plain',lineheight=1.2))
# Optional export names allow a typography-only redraw without touching other panels.
requested_stems <- commandArgs(trailingOnly=TRUE)
save_diagram <- function(stem,w,h,draw) {
 if (length(requested_stems) && !stem %in% requested_stems) return(invisible(NULL))
 FIG_PDF_DEVICE(file.path(out,paste0(stem,'.pdf')),width=w/72,height=h/72);grid.newpage();draw();dev.off()
 png(file.path(out,paste0(stem,'.png')),width=w/72,height=h/72,units='in',res=600,type='quartz');grid.newpage();draw();dev.off()
}
save_diagram('Fig1A_Experimental_Strategy',420,210,function(){
 label(.5,.95,'Comparison of dMIC60-WT and dMIC60-CS',TRUE)
 box(.5,.79,.54,.18,'')
 label(.5,.82,'Expression in a null genetic background')
 label(.5,.76,FIG_NULL_BACKGROUND_LABEL)
 link(.37,.70,.26,.59);link(.63,.70,.74,.59)
 box(.26,.49,.44,.20,'Drosophila\nFemale and male RNA-seq\nFemale physiology and microscopy')
 box(.74,.49,.44,.20,'HeLa cells\nVehicle or hydrogen peroxide\nCell-based fluorescence and MTT assays')
 link(.26,.39,.26,.28);link(.74,.39,.74,.28)
 box(.26,.16,.44,.23,'Gene expression and functional annotations\nSleep, activity and locomotion\nSurvival and mitochondrial measurements')
 box(.74,.16,.44,.23,'TIMELESS/DAPI fluorescence\nMTT metabolic reducing activity\nExpression and transfection controls')
})
save_diagram('FigS1A_RNAseq_Workflow',270,375,function(){
 box(.5,.92,.86,.11,'RNA-seq: 12 pooled biological libraries\n3 per genotype and sex; 5 flies per library')
 link(.5,.865,.5,.82)
 box(.5,.765,.86,.11,'Gene-by-library count matrix\nNo manual count prefilter')
 link(.33,.71,.27,.65);link(.67,.71,.73,.65)
 box(.27,.58,.43,.14,'Sex-specific DESeq2 fits\nCS versus WT\nWald tests')
 box(.73,.58,.43,.14,'Design-blind rlog\nAll 12 libraries\nVisualization only')
 link(.27,.51,.27,.45);link(.73,.51,.73,.45)
 box(.27,.37,.43,.16,'Independent filtering\nand BH correction\nwithin each sex')
 box(.73,.37,.43,.16,'PCA / classical MDS\nEuclidean distances\nGene heatmaps: row z scores')
 link(.27,.29,.27,.23)
 box(.27,.145,.43,.17,'')
 label(.27,.20,'DEG classification');label(.27,.165,expression(italic(p)[BH]<0.05))
 label(.27,.127,'Absolute log2 fold change');label(.27,.092,'at least 0.58')
 box(.73,.145,.43,.17,'')
 label(.73,.20,'Heatmap selection');label(.73,.165,'Top 30 per direction')
 label(.73,.127,expression(italic(p)[BH]<0.05));label(.73,.092,'Ties: gene symbol')
 link(.46,.37,.515,.145,dashed=TRUE)
})
save_diagram('Fig4C_Working_Model',420,245,function(){
 label(.5,.955,'Working model: mechanism remains to be tested',TRUE)
 box(.17,.78,.28,.20,'Oxidation-resistant\ndMIC60-CS',fill=fig_lighten(FIG_COLORS['mutant'],.7))
 box(.50,.78,.25,.20,'Proposed\nmitochondrial signal')
 box(.83,.78,.28,.20,'Nuclear gene\nexpression changes')
 link(.31,.78,.375,.78,dashed=TRUE);link(.625,.78,.69,.78,dashed=TRUE)
 label(.5,.62,'Dashed arrows indicate proposed steps.')
 label(.5,.51,'Associated observations; causal links untested',TRUE)
 box(.26,.29,.45,.30,'Female flies\nOxidative-metabolism annotations\nSelected genome-maintenance genes\nMore nighttime sleep; less nighttime activity\nImproved locomotor performance')
 box(.74,.29,.45,.30,'HeLa cells: exploratory measurements\nNuclear TIMELESS/DAPI fluorescence\nNormalized MTT signals\nIndependent replication needs confirmation')
 label(.5,.065,'Signal identity and conservation across models remain unresolved.')
})
